collections:
  features:
    output: true
  team:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

tagline: "Your data. On your terms. In your pocket."
sub_tagline: "It's your data; what're you gonna do about it?"

feature_description: "This is where our list of planned features will go but for now, we are keeping our feature roadmap under wraps. Sign up for the waitlist and you'll be the first to know what we've got coming for you."
team_description: "Scrillionaire is built by a small team of contributors from the Pacific Northwest (aka Cascadia). If you think you'd be interested in helping us get Scrillionaire into the hands of users faster, <a href=\"mailto:sup@Scrillionaire.io\">drop us a line</a>."

reCaptcha_public_key: 6Le7e1seAAAAAOoBqI65eg8zBunM1qcE1M_TgsTm

form_endpoint: https://getform.io/f/DbDGpAal
email_signup_cta: Join the Waitlist
email_signup_title: You wanna be a
email_signup_copy: Shoot us your email and we'll shoot you the **Beta** when it's ready!

